### ISSUE TITLE
Diameter or pixel scale parameter

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/eidos#13]
I think a nice enhancement would be to require the user to specify the number of pixels, but then optionally either the beam diameter or the pixel scale. The latter is more consistent with what a FITS header actually contains, and would make it easier to precisely and automatically map a primary beam model to a particular image.

(You could also cater for non-square pixels, and unequal image extents, for those rare people who use such things.)

Thanks.

**Comment by kmbasad** [comment]
Sorry for the delay. I have pushed a new version of EIDOS today with 10 degree beams. Will try to add this functionality soon too.

**Comment by kmbasad** [comment]
Added this option. Users can specify any two of these 3 options now: diameter, number of pixels, pixel scale.

**Comment by IanHeywood** [comment]
Having problems with the -r / -f approach:

```
$ eidos -p 3112 -r 0.00041666666666666666666666 -f 1065.2978515625 -S I
Traceback (most recent call last):
  File "/home/heywood-l/venv/eidos/bin/eidos", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/heywood-l/Software/eidos/bin/eidos", line 6, in <module>
    create_beam.main(sys.argv[1:])
  File "/home/heywood-l/Software/eidos/eidos/create_beam.py", line 81, in main
    params, freqs = zernike_parameters(filename, args.pixels, args.diameter, args.thresh)
  File "/home/heywood-l/Software/eidos/eidos/create_beam.py", line 18, in zernike_parameters
    Npix = int(diameter_orig/(diameter/npix))
ZeroDivisionError: float division by zero
```

**Comment by IanHeywood** [comment]
I think this is the problem:

https://github.com/ratt-ru/eidos/blob/master/eidos/create_beam.py#L74

The diameter (in degrees) is forced to be an integer at this point. Removed the explicit `int` and it's running now.
