### ISSUE TITLE
Numpy-related (?) error on latest version

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/eidos#18]
```
$ eidos -p 256 -d 10 -f 1070
Traceback (most recent call last):
  File "/home/ianh/.local/bin/eidos", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ianh/Software/eidos/bin/eidos", line 6, in <module>
    create_beam.main(sys.argv[1:])
  File "/home/ianh/Software/eidos/eidos/create_beam.py", line 68, in main
    params, freqs = zernike_parameters(filename, args.pixels, args.diameter, args.thresh)
  File "/home/ianh/Software/eidos/eidos/create_beam.py", line 15, in zernike_parameters
    C = np.load(filename, encoding='latin1').item()
  File "/home/ianh/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 447, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/ianh/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 692, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

**Comment by IanHeywood** [comment]
```
def zernike_parameters(filename, npix=256, diameter=10, thr=20):
    C = np.load(filename, encoding='latin1',allow_pickle=True).item()
```

in `create_beam.py` seems to fix it.

**Comment by kmbasad** [comment]
Thanks. I do not get this error but to be sure I have added the allow_pickle option.
