### ISSUE TITLE
trying to get L-band Stokes I model

### ISSUE THREAD

**Issue by ktrehaeven** [ratt-ru/eidos#28]
Hi

I'm trying to get a model of the Stokes I meerkat primary beam, but when I run `eidos -p 5500 -r 0.00036111111111111115 -f 1283 -c mh -P out -S I` I get the following error.

Traceback (most recent call last):
  File "/home/trehaeven/venv/bin/eidos", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/trehaeven/software/eidos/bin/eidos", line 6, in <module>
    create_beam.main(sys.argv[1:])
  File "/home/trehaeven/software/eidos/eidos/create_beam.py", line 87, in main
    params, freqs = zernike_parameters(filename, args.pixels, args.diameter, args.thresh)
  File "/home/trehaeven/software/eidos/eidos/create_beam.py", line 20, in zernike_parameters
    return np.array(params), C['nu']
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (8001, 4) + inhomogeneous part.
 
Not sure whats going on here.

**Comment by rramij** [comment]
I am having similar problem with -o8 option.

`eidos -p 8192 -r 0.000277778 -f 856 1712 9 -o8 -P meerkat_pb_jones_cube_95channels`

This is returning similar error:

`Traceback (most recent call last):
  File "/home/rramij/.local/bin/eidos", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/rramij/eidos/bin/eidos", line 6, in <module>
    create_beam.main(sys.argv[1:])
  File "/home/rramij/eidos/eidos/create_beam.py", line 87, in main
    params, freqs = zernike_parameters(filename, args.pixels, args.diameter, args.thresh)
  File "/home/rramij/eidos/eidos/create_beam.py", line 20, in zernike_parameters
    return np.array(params), C['nu']
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (8001, 4) + inhomogeneous part.
`

Not sure how to resolve this.

**Comment by rramij** [comment]
After upgrading eidos from 1.1.0 to 1.1.2 it seems to be running...
Let's see the result.

**Comment by rramij** [comment]
There is no control over parallelisation. The above eidos options seem to overwhelm the computing resource.
All CPU cores as well as RAM and SWAP are used up, and the terminal stopped responding.
I think option to resource allocation is necessary.
![Image](https://github.com/user-attachments/assets/47379a82-c9e6-4467-8993-adbba0d82fe5)

**Comment by bennahugo** [comment]
Considering this will result in a cube 760.0GB in size I'm not surprised it runs out of memory. Any reason why you have the beam done per pixel for 95 channels. We rarely exceed 10x10 facets, so you may want a 25x25 px cube of the beam?

**Comment by bennahugo** [comment]
Remember the frequency slices are in MHz

**Comment by rramij** [comment]
I will be making a 8192 x 8192 pixel image with 1 arcsec pixel in DDFacet. I thought I need to have one-to-one matching size primary beam fits files.
Is a 256 x 256 pb cube with the required primary beam diameter enough for this purpose?

**Comment by bennahugo** [comment]
It gets linearly interpolated. So yes it is more than sufficient. Just make
sure you cover at least the extent of the image

**Comment by rramij** [comment]
Another quick clarification. How many channels are sufficient for MeerKAT L-band (full 856 MHz bandwidth)?
Is the following parameter choice good enough for my purpose?
`eidos -p 25 -d 4 -f 856 1712 9 -o8 -P meerkat_pb_jones_cube_95channels`

A suggestion on good practice would be appreciated.
