### ISSUE TITLE
meerkat_coeff_dict.npy missing from installation MANIFEST

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/eidos#8]
```
(venv) > $ eidos -o8 -p 257 -f 850 1800 10 -N                                                                                
Traceback (most recent call last):
  File "/scratch/bhugo/venv/bin/eidos", line 6, in <module>
    create_beam.main(sys.argv[1:])
  File "/scratch/bhugo/venv/local/lib/python2.7/site-packages/eidos/create_beam.py", line 31, in main
    coeffs = np.load(args.coefficients_file).item()
  File "/scratch/bhugo/venv/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '/scratch/bhugo/venv/local/lib/python2.7/site-packages/eidos/data/meerkat_coeff_dict.npy'
```

**Comment by bennahugo** [comment]
Requires a MANIFEST file to be added

**Comment by gigjozsa** [comment]
Same problem here.
